### ISSUE TITLE
Redis section in `Directive.yaml` in is not read/used

### ISSUE THREAD

**Issue by k33g** [suborbital/atmo#165]
Only the default in-memory cache is used, even if the redis connection is declared:

```yaml
identifier: com.suborbital.services
appVersion: v0.1.0
atmoVersion: v0.4.4

connections:
  redis:
    serverAddress: redis-server:6379

handlers:
  - type: request
    resource: /create
    method: POST
    steps:
      - fn: create
  - type: request
    resource: /read/:key
    method: GET
    steps:
       - fn: read
```

The create function adds a key/value to the cache, and the read function reads the value associated with the key. But when I run this:

```shell
redis-cli
keys *
```
I get nothing. The cache methods are ok, but nothing is stored in the Redis database

**Comment by k33g** [comment]
I tried with a username and password, but same problem (an no error message):

```yaml
connections:
  redis:
    serverAddress: redis-server:6379
    username: default
    password: ""
```

**Comment by elliott-davis** [comment]
I wonder if this is related to #166. Seems like maybe `connections` isn't being parsed correctly

**Comment by k33g** [comment]
I tried with this image `suborbital/atmo:v0.4.2` and it's ok, after, it's ko

**Comment by k33g** [comment]
👋 @k33g I used Docker compose (it worked before)

```yaml
services:
  redis-server:
    image: redis:latest
    container_name: redis-server
    ports:
      - 6379:6379

  atmo-server:
    image: suborbital/atmo:latest
    container_name: atmo-server
    entrypoint: atmo
    environment:
      - ATMO_HTTP_PORT=8080
    ports:
      - 8080:8080
    volumes:
      - /workspace/atmo-redis-workspace/services:/home/atmo

```

**Comment by javorszky** [comment]
Okay, that's useful! Let me test

**Comment by javorszky** [comment]
Right, interesting. I can confirm that with 0.4.6 it doesn't work with the given docker compose file. With 0.4.7, which was released yesterday, it seems to work.

Here's what I've done to test it:
1. created a project with `subo create project <name>`
1. create two runnables named `create` and `read` in typescript using `subo create runnable create --lang=ts`.
  1. The create gets a json by the structure of `{"key": "somekey", "value": "somevalue"}`, and will store the value at key with a ttl being null at whatever cache the runnable has access to.
  2. `read` will parse the url param and fetch the value from the cache by that key
2. I copied the connections part into the directive.yaml file.
3. Built the project with `subo build .`
4. created a folder named `intodocker`, and copied the `runnables.wasm.zip` file into that folder
5. copied your docker compose file. The only change I did was the volume path so the local points to the `intodocker` folder where the only file is the runnables wasm zip
6. brought up that with `docker compose up`
7. in a separate terminal I listed the docker containers with `docker ps`, and execced into the redis with `docker exec -it <sha of running redis> redis-cli`
8. listed all the keys with `keys *`, came back with an empty array
9. using postman, I sent a POST request to `http://localhost:8080/create` with a following payload: `{"key": "something", "value": "somevalue"}`
10. The response is 200, and I can read it back out using the GET endpoint
11. However the redis changes whether the version in the docker compose is latest (currently 0.4.7), 0.4.6, or 0.4.7 explicitly
  1. When it's 0.4.6, after sending the POST request, a `keys *` does not return the newly inserted entry
  2. When it's either latest, or 0.4.7, the `keys *` does return the newly inserted entry

I'm investigating what change between the two versions is responsible for fixing this, but so far nothing obvious is standing out. The few changes between them have to do with env var parsing, more options for atmo startup, and a change to the database connections parsing, but not the redis one.

Once we find the source, I'll add what the issue was and the solution, but for now the `latest` and `0.4.7` should restore functionality.

Can you double check on your end as well? 🙂

**Comment by javorszky** [comment]
Oh, I think it's this one: https://github.com/suborbital/atmo/commit/a45982d7c8512862623f41d2ba9d079ceda617f4

The `source.Connections` call using the ident and version instead of the ident and namespace.

**Comment by k33g** [comment]
I'm at the airport right now, but I will test this weekend (I've an idea of blog post about Atmo, and if the Redis cx is ok, it will help me a lot)

**Comment by javorszky** [comment]
Sweet, thank you! Safe flight, and talk next week 🙂

**Comment by k33g** [comment]
@javorszky I did the test with the latest version of the image, and it works perfectly 👍 👏

**Comment by javorszky** [comment]
Awesome, thank you for double checking it. I'll close this one as solved.

For the folks running into the same issue with version 0.4.6: the solution is to update to 0.4.7 (valid at the time). If the issue appears in a version later than that, open a new issue 🙂

**Comment by k33g** [comment]
@javorszky I have the impression that we can only use the default port of Redis (`6379 : 6379`). If I try with another one (`6380 : 6379`) nothing is stored in Redis

**Comment by javorszky** [comment]
@k33g Yep, reproduced the issue. Would you like to create a new Github issue for it, or do you want me to do that? 🙂

**Comment by javorszky** [comment]
Moving the solution to running redis on a different port over from Discord for future folks who ran into the same issue:

here's the docker compose file fragment:
```yaml
redis-server:
    image: redis:latest
    command: "/usr/local/etc/redis/redis.conf"
    container_name: redis-server
    ports:
      - 7777:17221
    volumes:
      - ./redis:/usr/local/etc/redis
```
I created a file in `./redis/redis.conf` with the following content:
```
port 17221
```

The idea behind it is that without any extra configuration of the redis server in the docker image, it will always start up on port 6379. That port is always exposed (it's baked into their Dockerfiles (https://github.com/docker-library/redis/blob/master/Dockerfile-alpine.template#L103)).

To add configuration, I had to change the command passed to the docker image to take advantage of what the docker-entrypoint.sh does for us. One of the shorthands is that if I provide the path of a configuration file mounted into the image, it will execute redis-server /path/to/conf/file instead, see  https://github.com/docker-library/redis/blob/master/docker-entrypoint.sh#L5-L8

More documentation for redis.conf options here: https://redis.io/docs/manual/config/
