### ISSUE TITLE
Refactor directive.yaml

### ISSUE THREAD

**Issue by ospencer** [suborbital/atmo#214]
`directive.yaml` should be replaced with `velocity.yaml`. This accounts for two separate changes, one to the file itself, as well as the struct that represents a directive (and the related changes throughout Atmo). This does not include changes to the cli or other projects that consume directives.

The `velocity.yaml` file found at the project root includes some project metadata and optional `handlers`, `workflows`, `capabilities`, `queries`, and `connections` stanzas.

### Required fields

Required fields are `version` (indicating the spec version) and `identifier`(i.e. the application identifier):

```yaml
version: 1
identifier: com.suborbital.guide
```

💡 Note that appVersion is no longer a field of the directive as it is calculated rather than set

### Handlers

```yaml
handlers:
	- type: request
		method: POST
	  resource: /api/users/add-user
	  fn: /api/users/add-user
	
	- type: request
		method: POST
	  resource: /api/users/add-user
	  workflow: PostSignupActions
```

Handlers now reference a single function or a workflow rather than having `steps`, see `workflows` below.

By default, a handler uses the `request` type, but they can also be set to a different type such as `websocket` or `stream` (which requires a named `connection`).

```yaml
- type: stream
  source: nats-main
  resource: user.created
  fn: record-signup
	sink:
		source: nats-main
		resource: signup-completed
```

The optional `sink` field can be used to direct the output of any `stream` type handler. If no `sink` is provided, the output of the function is discarded.

### Workflows

The new `workflows` stanza replaces the previous multi-step requests. Workflows have unique names rather than URIs. They are called by referencing them in a handler using the `workflow` field instead of the `fn` field (see example above).

The `steps` field of a `workflow` is an array of two kinds of steps: `fn` or `group`. Steps are executed sequentially, with `group` steps executing multiple sub-functions concurrently. The behavior of a workflow is the same as a multi-step request handler.

```yaml
workflows:
	- name: PostSignupActions
		steps:
			- fn: /actions/mark-signup-completed
			- fn: /actions/send-signup-completed-email
```

### Scheduled workflows

Replacing `schedules` from Atmo, workflows can optionally include a `schedule`:

```yaml
workflows:
	- name: PostSignupActions
		steps:
			- fn: /actions/mark-signup-completed
			- fn: /actions/send-signup-completed-email
		schedule:
			every:
		     hours: 1
	    state:
	      somekey: someval
```

The behavior of scheduled workflows is the same as before, and `state` can be used to seed the sequence with key/value pairs.

### Connections

The `connections` field includes the available external resources such as databases, caches, etc.

```yaml
connections:
  - type: "nats"
		name: "nats-main"
    serverAddress: "nats://localhost:4222"
  - type: "kafka"
		name: "kafka-main"
    brokerAddress: "localhost:9092"
	- type: "redis"
		name: "cache"
		address: "localhost:4242"
```

💡 Note that `connections` is now an array, and each entry has a `type` and `name`, plus type-specific fields.
